### PR TITLE
rename clearCache message to clearTemp

### PR DESCRIPTION
**Pull request by JDuqn**

### CODE REVIEW

**Comment by hubjac1** [comment]
Hi @JDuqn , Why did you changed the version number? They has to  be change by lerna in the lerna publish.

**Comment by JDuqn** [comment]
@hubjac1 Sorry, I'm still new and don't know how everything works yet.
I just followed what was done in the previous similar changes.
I just commited to revert the changes in version number.
@ArnaudGathy is gonna guide me through the publishing part.
Thanks.

**Comment by ArnaudGathy** [comment]
What are you doing here @hubjac1 ? :o

**Comment by ArnaudGathy** [comment]
To publish :

Get acces to the NPM repository (ask Antoine)
- npm login
- npm run publish
- Bump the version of the neede package where you use ozone-components

**Pull request merged**
